name: lint and test
on:
  push:
    paths:
      - "**/*.js"
      - "**/*.ts"
      - "deno.*"
      - ".github/workflows/deno.yml"
  pull_request:
    paths:
      - "**/*.ts"
      - "**/*.js"
jobs:
  testingWithDeno:
    runs-on: ubuntu-latest
    steps:
      - name: Working version
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Fuentes
        uses: actions/checkout@v4
      - name: Lint
        run: deno task lint
      - name: Install external tools for testing
        run: sudo apt install zbar-tools
      - name: test
        run: deno task test
