name: "Check markdown for spelling and formatting errors"
on:
  push:
    paths:
      - "**/*.md"
      - "*.md"
      - assets/*.txt

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out fuentes
        uses: actions/checkout@v4
      - name: "Check format errors"
        uses: articulate/actions-markdownlint@v1
      - uses: rojopolis/spellcheck-github-actions@v0
        name: "Checks spelling"
        with:
          source_files: "README.md docs/*.md"
          task_name: Spellcheck
